/* ============================================================
   rosters.js — plantillas de referencia (temporada 2024/25)
   Premier League (20 equipos) + Bundesliga (18 equipos)
   Expuesto en window.FC.data.ROSTERS
   ============================================================ */
(function () {
  window.FC = window.FC || {};
  window.FC.data = window.FC.data || {};

  window.FC.data.ROSTERS = {

    /* ===== PREMIER LEAGUE ===== */

    "Arsenal": [
      {name:"David Raya",pos:"GK",age:29,ovr:85,nat:"España"},
      {name:"Aaron Ramsdale",pos:"GK",age:26,ovr:80,nat:"Inglaterra"},
      {name:"Ben White",pos:"RB",age:26,ovr:83,nat:"Inglaterra"},
      {name:"Takehiro Tomiyasu",pos:"RB",age:25,ovr:79,nat:"Japón"},
      {name:"William Saliba",pos:"CB",age:23,ovr:87,nat:"Francia"},
      {name:"Gabriel Magalhães",pos:"CB",age:26,ovr:85,nat:"Brasil"},
      {name:"Jakub Kiwior",pos:"CB",age:24,ovr:76,nat:"Polonia"},
      {name:"Oleksandr Zinchenko",pos:"LB",age:27,ovr:82,nat:"Ucrania"},
      {name:"Kieran Tierney",pos:"LB",age:27,ovr:78,nat:"Escocia"},
      {name:"Thomas Partey",pos:"CDM",age:31,ovr:84,nat:"Ghana"},
      {name:"Jorginho",pos:"CDM",age:32,ovr:80,nat:"Italia"},
      {name:"Martin Ødegaard",pos:"CAM",age:25,ovr:88,nat:"Noruega"},
      {name:"Kai Havertz",pos:"CAM",age:25,ovr:82,nat:"Alemania"},
      {name:"Declan Rice",pos:"CM",age:25,ovr:86,nat:"Inglaterra"},
      {name:"Fabio Vieira",pos:"CM",age:23,ovr:76,nat:"Portugal"},
      {name:"Bukayo Saka",pos:"RW",age:22,ovr:89,nat:"Inglaterra"},
      {name:"Gabriel Martinelli",pos:"LW",age:23,ovr:84,nat:"Brasil"},
      {name:"Leandro Trossard",pos:"LW",age:29,ovr:82,nat:"Bélgica"},
      {name:"Gabriel Jesus",pos:"ST",age:27,ovr:82,nat:"Brasil"},
      {name:"Eddie Nketiah",pos:"ST",age:25,ovr:76,nat:"Inglaterra"},
    ],

    "Aston Villa": [
      {name:"Emiliano Martínez",pos:"GK",age:32,ovr:87,nat:"Argentina"},
      {name:"Robin Olsen",pos:"GK",age:34,ovr:76,nat:"Suecia"},
      {name:"Matty Cash",pos:"RB",age:27,ovr:79,nat:"Polonia"},
      {name:"Ezri Konsa",pos:"CB",age:26,ovr:81,nat:"Inglaterra"},
      {name:"Pau Torres",pos:"CB",age:27,ovr:82,nat:"España"},
      {name:"Tyrone Mings",pos:"CB",age:31,ovr:78,nat:"Inglaterra"},
      {name:"Lucas Digne",pos:"LB",age:31,ovr:79,nat:"Francia"},
      {name:"Alex Moreno",pos:"LB",age:28,ovr:76,nat:"España"},
      {name:"Youri Tielemans",pos:"CM",age:27,ovr:82,nat:"Bélgica"},
      {name:"Douglas Luiz",pos:"CM",age:26,ovr:83,nat:"Brasil"},
      {name:"John McGinn",pos:"CM",age:29,ovr:80,nat:"Escocia"},
      {name:"Moussa Diaby",pos:"RW",age:25,ovr:83,nat:"Francia"},
      {name:"Leon Bailey",pos:"LW",age:26,ovr:80,nat:"Jamaica"},
      {name:"Emiliano Buendía",pos:"CAM",age:27,ovr:79,nat:"Argentina"},
      {name:"Nicolò Zaniolo",pos:"CAM",age:25,ovr:78,nat:"Italia"},
      {name:"Ollie Watkins",pos:"ST",age:28,ovr:86,nat:"Inglaterra"},
      {name:"Jhon Durán",pos:"ST",age:21,ovr:74,nat:"Colombia"},
      {name:"Ross Barkley",pos:"CM",age:30,ovr:74,nat:"Inglaterra"},
    ],

    "Bournemouth": [
      {name:"Neto",pos:"GK",age:35,ovr:80,nat:"Brasil"},
      {name:"Mark Travers",pos:"GK",age:25,ovr:74,nat:"Irlanda"},
      {name:"Adam Smith",pos:"RB",age:33,ovr:73,nat:"Inglaterra"},
      {name:"Lloyd Kelly",pos:"CB",age:25,ovr:76,nat:"Inglaterra"},
      {name:"Chris Mepham",pos:"CB",age:27,ovr:73,nat:"Gales"},
      {name:"Marcos Senesi",pos:"CB",age:27,ovr:76,nat:"Argentina"},
      {name:"Milos Kerkez",pos:"LB",age:21,ovr:76,nat:"Hungría"},
      {name:"Ryan Christie",pos:"CM",age:29,ovr:75,nat:"Escocia"},
      {name:"Lewis Cook",pos:"CDM",age:27,ovr:76,nat:"Inglaterra"},
      {name:"Philip Billing",pos:"CM",age:28,ovr:75,nat:"Dinamarca"},
      {name:"Marcus Tavernier",pos:"RM",age:25,ovr:74,nat:"Inglaterra"},
      {name:"Dango Ouattara",pos:"RW",age:22,ovr:76,nat:"Burkina Faso"},
      {name:"Antoine Semenyo",pos:"RW",age:24,ovr:74,nat:"Ghana"},
      {name:"Justin Kluivert",pos:"LW",age:25,ovr:77,nat:"Países Bajos"},
      {name:"Enes Ünal",pos:"ST",age:27,ovr:75,nat:"Turquía"},
      {name:"Dominic Solanke",pos:"ST",age:26,ovr:78,nat:"Inglaterra"},
      {name:"Julián Araujo",pos:"RB",age:22,ovr:73,nat:"México"},
    ],

    "Brentford": [
      {name:"Mark Flekken",pos:"GK",age:31,ovr:80,nat:"Países Bajos"},
      {name:"Thomas Strakosha",pos:"GK",age:29,ovr:75,nat:"Albania"},
      {name:"Aaron Hickey",pos:"RB",age:22,ovr:77,nat:"Escocia"},
      {name:"Kristoffer Ajer",pos:"CB",age:26,ovr:78,nat:"Noruega"},
      {name:"Ben Mee",pos:"CB",age:34,ovr:76,nat:"Inglaterra"},
      {name:"Ethan Pinnock",pos:"CB",age:31,ovr:76,nat:"Jamaica"},
      {name:"Rico Henry",pos:"LB",age:26,ovr:76,nat:"Inglaterra"},
      {name:"Christian Nørgaard",pos:"CDM",age:30,ovr:79,nat:"Dinamarca"},
      {name:"Mathias Jensen",pos:"CM",age:28,ovr:76,nat:"Dinamarca"},
      {name:"Frank Onyeka",pos:"CM",age:26,ovr:74,nat:"Nigeria"},
      {name:"Vitaly Janelt",pos:"CM",age:26,ovr:74,nat:"Alemania"},
      {name:"Keane Lewis-Potter",pos:"LW",age:23,ovr:74,nat:"Inglaterra"},
      {name:"Yoane Wissa",pos:"LW",age:27,ovr:77,nat:"Congo"},
      {name:"Bryan Mbeumo",pos:"RW",age:24,ovr:80,nat:"Camerún"},
      {name:"Ivan Toney",pos:"ST",age:28,ovr:82,nat:"Inglaterra"},
      {name:"Mikkel Damsgaard",pos:"CAM",age:24,ovr:76,nat:"Dinamarca"},
      {name:"Neal Maupay",pos:"ST",age:28,ovr:74,nat:"Francia"},
    ],

    "Brighton": [
      {name:"Jason Steele",pos:"GK",age:33,ovr:76,nat:"Inglaterra"},
      {name:"Bart Verbruggen",pos:"GK",age:22,ovr:78,nat:"Países Bajos"},
      {name:"Tariq Lamptey",pos:"RB",age:23,ovr:77,nat:"Ghana"},
      {name:"Joel Veltman",pos:"RB",age:32,ovr:76,nat:"Países Bajos"},
      {name:"Lewis Dunk",pos:"CB",age:32,ovr:79,nat:"Inglaterra"},
      {name:"Adam Webster",pos:"CB",age:29,ovr:76,nat:"Inglaterra"},
      {name:"Jan Paul van Hecke",pos:"CB",age:24,ovr:77,nat:"Países Bajos"},
      {name:"Pervis Estupiñán",pos:"LB",age:26,ovr:80,nat:"Ecuador"},
      {name:"Billy Gilmour",pos:"CDM",age:23,ovr:76,nat:"Escocia"},
      {name:"Pascal Groß",pos:"CM",age:33,ovr:79,nat:"Alemania"},
      {name:"Jakub Moder",pos:"CM",age:25,ovr:74,nat:"Polonia"},
      {name:"Solly March",pos:"RM",age:29,ovr:77,nat:"Inglaterra"},
      {name:"Simon Adingra",pos:"RW",age:22,ovr:76,nat:"Costa de Marfil"},
      {name:"Facundo Buonanotte",pos:"CAM",age:20,ovr:74,nat:"Argentina"},
      {name:"Mahmoud Dahoud",pos:"CM",age:28,ovr:76,nat:"Alemania"},
      {name:"João Pedro",pos:"ST",age:22,ovr:79,nat:"Brasil"},
      {name:"Danny Welbeck",pos:"ST",age:33,ovr:74,nat:"Inglaterra"},
      {name:"Evan Ferguson",pos:"ST",age:19,ovr:76,nat:"Irlanda"},
    ],

    "Burnley": [
      {name:"James Trafford",pos:"GK",age:21,ovr:74,nat:"Inglaterra"},
      {name:"Arijanet Muric",pos:"GK",age:25,ovr:73,nat:"Kosovo"},
      {name:"Connor Roberts",pos:"RB",age:28,ovr:73,nat:"Gales"},
      {name:"Dara O'Shea",pos:"CB",age:25,ovr:73,nat:"Irlanda"},
      {name:"Jordan Beyer",pos:"CB",age:24,ovr:72,nat:"Alemania"},
      {name:"Luke McNally",pos:"CB",age:24,ovr:70,nat:"Irlanda"},
      {name:"Charlie Taylor",pos:"LB",age:30,ovr:72,nat:"Inglaterra"},
      {name:"Vitinho",pos:"RB",age:23,ovr:72,nat:"Brasil"},
      {name:"Josh Brownhill",pos:"CM",age:28,ovr:74,nat:"Inglaterra"},
      {name:"Jack Cork",pos:"CDM",age:35,ovr:72,nat:"Inglaterra"},
      {name:"Sander Berge",pos:"CDM",age:26,ovr:75,nat:"Noruega"},
      {name:"Johann Berg Gudmundsson",pos:"RM",age:33,ovr:73,nat:"Islandia"},
      {name:"Lyle Foster",pos:"ST",age:23,ovr:73,nat:"Sudáfrica"},
      {name:"Zeki Amdouni",pos:"ST",age:23,ovr:74,nat:"Suiza"},
      {name:"Wilson Odobert",pos:"LW",age:19,ovr:73,nat:"Francia"},
      {name:"Jay Rodriguez",pos:"ST",age:34,ovr:71,nat:"Inglaterra"},
      {name:"David Datro Fofana",pos:"LW",age:21,ovr:72,nat:"Costa de Marfil"},
    ],

    "Chelsea": [
      {name:"Robert Sánchez",pos:"GK",age:26,ovr:81,nat:"España"},
      {name:"Djordje Petrovic",pos:"GK",age:24,ovr:78,nat:"Serbia"},
      {name:"Reece James",pos:"RB",age:24,ovr:85,nat:"Inglaterra"},
      {name:"Malo Gusto",pos:"RB",age:21,ovr:78,nat:"Francia"},
      {name:"Thiago Silva",pos:"CB",age:40,ovr:83,nat:"Brasil"},
      {name:"Wesley Fofana",pos:"CB",age:23,ovr:81,nat:"Francia"},
      {name:"Benoît Badiashile",pos:"CB",age:23,ovr:78,nat:"Francia"},
      {name:"Axel Disasi",pos:"CB",age:26,ovr:78,nat:"Francia"},
      {name:"Ben Chilwell",pos:"LB",age:27,ovr:81,nat:"Inglaterra"},
      {name:"Marc Cucurella",pos:"LB",age:26,ovr:79,nat:"España"},
      {name:"Moises Caicedo",pos:"CDM",age:22,ovr:84,nat:"Ecuador"},
      {name:"Enzo Fernández",pos:"CM",age:23,ovr:84,nat:"Argentina"},
      {name:"Conor Gallagher",pos:"CM",age:24,ovr:80,nat:"Inglaterra"},
      {name:"Christopher Nkunku",pos:"CAM",age:26,ovr:84,nat:"Francia"},
      {name:"Cole Palmer",pos:"CAM",age:22,ovr:87,nat:"Inglaterra"},
      {name:"Raheem Sterling",pos:"LW",age:29,ovr:82,nat:"Inglaterra"},
      {name:"Mykhailo Mudryk",pos:"LW",age:23,ovr:79,nat:"Ucrania"},
      {name:"Nicolas Jackson",pos:"ST",age:23,ovr:80,nat:"Senegal"},
      {name:"Armando Broja",pos:"ST",age:22,ovr:74,nat:"Albania"},
      {name:"Noni Madueke",pos:"RW",age:22,ovr:78,nat:"Inglaterra"},
    ],

    "Crystal Palace": [
      {name:"Dean Henderson",pos:"GK",age:27,ovr:79,nat:"Inglaterra"},
      {name:"Sam Johnstone",pos:"GK",age:31,ovr:76,nat:"Inglaterra"},
      {name:"Nathaniel Clyne",pos:"RB",age:33,ovr:73,nat:"Inglaterra"},
      {name:"Joel Ward",pos:"RB",age:34,ovr:72,nat:"Inglaterra"},
      {name:"Marc Guéhi",pos:"CB",age:23,ovr:81,nat:"Inglaterra"},
      {name:"Joachim Andersen",pos:"CB",age:28,ovr:80,nat:"Dinamarca"},
      {name:"Chris Richards",pos:"CB",age:24,ovr:74,nat:"Estados Unidos"},
      {name:"Tyrick Mitchell",pos:"LB",age:24,ovr:77,nat:"Inglaterra"},
      {name:"Cheick Doucouré",pos:"CDM",age:24,ovr:78,nat:"Malí"},
      {name:"Eberechi Eze",pos:"CAM",age:25,ovr:83,nat:"Nigeria"},
      {name:"Michael Olise",pos:"RW",age:22,ovr:82,nat:"Francia"},
      {name:"Jordan Ayew",pos:"LW",age:32,ovr:74,nat:"Ghana"},
      {name:"Jean-Philippe Mateta",pos:"ST",age:27,ovr:79,nat:"Francia"},
      {name:"Odsonne Édouard",pos:"ST",age:26,ovr:76,nat:"Francia"},
      {name:"Jefferson Lerma",pos:"CDM",age:29,ovr:76,nat:"Colombia"},
      {name:"Will Hughes",pos:"CM",age:29,ovr:74,nat:"Inglaterra"},
      {name:"Jairo Riedewald",pos:"CM",age:27,ovr:73,nat:"Países Bajos"},
    ],

    "Everton": [
      {name:"Jordan Pickford",pos:"GK",age:30,ovr:83,nat:"Inglaterra"},
      {name:"Asmir Begovic",pos:"GK",age:37,ovr:73,nat:"Bosnia"},
      {name:"Séamus Coleman",pos:"RB",age:35,ovr:74,nat:"Irlanda"},
      {name:"Nathan Patterson",pos:"RB",age:22,ovr:73,nat:"Escocia"},
      {name:"Michael Keane",pos:"CB",age:31,ovr:76,nat:"Inglaterra"},
      {name:"James Tarkowski",pos:"CB",age:31,ovr:80,nat:"Inglaterra"},
      {name:"Jarrad Branthwaite",pos:"CB",age:22,ovr:78,nat:"Inglaterra"},
      {name:"Vitaliy Mykolenko",pos:"LB",age:24,ovr:77,nat:"Ucrania"},
      {name:"Ashley Young",pos:"LB",age:38,ovr:72,nat:"Inglaterra"},
      {name:"Idrissa Gueye",pos:"CDM",age:34,ovr:77,nat:"Senegal"},
      {name:"Amadou Onana",pos:"CM",age:23,ovr:79,nat:"Bélgica"},
      {name:"James Garner",pos:"CM",age:22,ovr:75,nat:"Inglaterra"},
      {name:"Abdoulaye Doucouré",pos:"CM",age:31,ovr:77,nat:"Francia"},
      {name:"Dwight McNeil",pos:"LM",age:24,ovr:77,nat:"Inglaterra"},
      {name:"Jack Harrison",pos:"LW",age:27,ovr:76,nat:"Inglaterra"},
      {name:"Beto",pos:"ST",age:25,ovr:74,nat:"Portugal"},
      {name:"Dominic Calvert-Lewin",pos:"ST",age:27,ovr:78,nat:"Inglaterra"},
      {name:"Youssef Chermiti",pos:"ST",age:20,ovr:72,nat:"Portugal"},
    ],

    "Fulham": [
      {name:"Bernd Leno",pos:"GK",age:32,ovr:81,nat:"Alemania"},
      {name:"Marek Rodák",pos:"GK",age:27,ovr:74,nat:"Eslovaquia"},
      {name:"Kenny Tete",pos:"RB",age:28,ovr:76,nat:"Países Bajos"},
      {name:"Tim Ream",pos:"CB",age:36,ovr:75,nat:"Estados Unidos"},
      {name:"Tosin Adarabioyo",pos:"CB",age:26,ovr:78,nat:"Nigeria"},
      {name:"Calvin Bassey",pos:"CB",age:24,ovr:76,nat:"Nigeria"},
      {name:"Antonee Robinson",pos:"LB",age:27,ovr:80,nat:"Estados Unidos"},
      {name:"Harrison Reed",pos:"CDM",age:29,ovr:76,nat:"Inglaterra"},
      {name:"Sasa Lukic",pos:"CM",age:27,ovr:75,nat:"Serbia"},
      {name:"Tom Cairney",pos:"CM",age:33,ovr:75,nat:"Escocia"},
      {name:"Andreas Pereira",pos:"CAM",age:28,ovr:78,nat:"Brasil"},
      {name:"Bobby Decordova-Reid",pos:"RM",age:31,ovr:74,nat:"Jamaica"},
      {name:"Harry Wilson",pos:"LM",age:27,ovr:74,nat:"Gales"},
      {name:"Willian",pos:"RW",age:35,ovr:75,nat:"Brasil"},
      {name:"Raúl Jiménez",pos:"ST",age:33,ovr:77,nat:"México"},
      {name:"Rodrigo Muniz",pos:"ST",age:23,ovr:75,nat:"Brasil"},
      {name:"Manor Solomon",pos:"LW",age:24,ovr:73,nat:"Israel"},
    ],

    "Leeds United": [
      {name:"Illan Meslier",pos:"GK",age:24,ovr:76,nat:"Francia"},
      {name:"Karl Darlow",pos:"GK",age:34,ovr:73,nat:"Inglaterra"},
      {name:"Luke Ayling",pos:"RB",age:32,ovr:74,nat:"Inglaterra"},
      {name:"Archie Gray",pos:"RB",age:18,ovr:73,nat:"Inglaterra"},
      {name:"Pascal Struijk",pos:"CB",age:25,ovr:76,nat:"Países Bajos"},
      {name:"Joe Rodon",pos:"CB",age:26,ovr:76,nat:"Gales"},
      {name:"Liam Cooper",pos:"CB",age:32,ovr:74,nat:"Escocia"},
      {name:"Junior Firpo",pos:"LB",age:27,ovr:75,nat:"España"},
      {name:"Sam Byram",pos:"RB",age:30,ovr:72,nat:"Inglaterra"},
      {name:"Glen Kamara",pos:"CDM",age:28,ovr:75,nat:"Finlandia"},
      {name:"Ethan Ampadu",pos:"CDM",age:23,ovr:76,nat:"Gales"},
      {name:"Georginio Rutter",pos:"CAM",age:22,ovr:77,nat:"Francia"},
      {name:"Willy Gnonto",pos:"LW",age:21,ovr:74,nat:"Italia"},
      {name:"Crysencio Summerville",pos:"LW",age:22,ovr:77,nat:"Países Bajos"},
      {name:"Patrick Bamford",pos:"ST",age:31,ovr:74,nat:"Inglaterra"},
      {name:"Joel Piroe",pos:"ST",age:24,ovr:75,nat:"Países Bajos"},
      {name:"Dan James",pos:"RM",age:26,ovr:73,nat:"Gales"},
    ],

    "Liverpool": [
      {name:"Alisson Becker",pos:"GK",age:31,ovr:90,nat:"Brasil"},
      {name:"Caoimhín Kelleher",pos:"GK",age:25,ovr:78,nat:"Irlanda"},
      {name:"Trent Alexander-Arnold",pos:"RB",age:25,ovr:88,nat:"Inglaterra"},
      {name:"Conor Bradley",pos:"RB",age:21,ovr:77,nat:"Irlanda del Norte"},
      {name:"Virgil van Dijk",pos:"CB",age:32,ovr:88,nat:"Países Bajos"},
      {name:"Joël Matip",pos:"CB",age:32,ovr:80,nat:"Camerún"},
      {name:"Ibrahima Konaté",pos:"CB",age:25,ovr:83,nat:"Francia"},
      {name:"Andrew Robertson",pos:"LB",age:30,ovr:85,nat:"Escocia"},
      {name:"Konstantinos Tsimikas",pos:"LB",age:28,ovr:78,nat:"Grecia"},
      {name:"Wataru Endo",pos:"CDM",age:31,ovr:79,nat:"Japón"},
      {name:"Alexis Mac Allister",pos:"CM",age:25,ovr:84,nat:"Argentina"},
      {name:"Dominik Szoboszlai",pos:"CM",age:23,ovr:83,nat:"Hungría"},
      {name:"Ryan Gravenberch",pos:"CM",age:22,ovr:80,nat:"Países Bajos"},
      {name:"Mohamed Salah",pos:"RW",age:32,ovr:90,nat:"Egipto"},
      {name:"Luis Díaz",pos:"LW",age:27,ovr:85,nat:"Colombia"},
      {name:"Diogo Jota",pos:"LW",age:27,ovr:84,nat:"Portugal"},
      {name:"Darwin Núñez",pos:"ST",age:25,ovr:83,nat:"Uruguay"},
      {name:"Cody Gakpo",pos:"LW",age:25,ovr:82,nat:"Países Bajos"},
      {name:"Harvey Elliott",pos:"CAM",age:21,ovr:76,nat:"Inglaterra"},
    ],

    "Manchester City": [
      {name:"Ederson",pos:"GK",age:30,ovr:90,nat:"Brasil"},
      {name:"Stefan Ortega",pos:"GK",age:31,ovr:78,nat:"Alemania"},
      {name:"Kyle Walker",pos:"RB",age:34,ovr:85,nat:"Inglaterra"},
      {name:"Rico Lewis",pos:"RB",age:19,ovr:76,nat:"Inglaterra"},
      {name:"Rúben Dias",pos:"CB",age:27,ovr:89,nat:"Portugal"},
      {name:"Manuel Akanji",pos:"CB",age:29,ovr:84,nat:"Suiza"},
      {name:"John Stones",pos:"CB",age:29,ovr:84,nat:"Inglaterra"},
      {name:"Nathan Aké",pos:"CB",age:29,ovr:82,nat:"Países Bajos"},
      {name:"Josko Gvardiol",pos:"LB",age:22,ovr:83,nat:"Croacia"},
      {name:"Rodri",pos:"CDM",age:28,ovr:91,nat:"España"},
      {name:"Kevin De Bruyne",pos:"CAM",age:33,ovr:91,nat:"Bélgica"},
      {name:"Bernardo Silva",pos:"CM",age:29,ovr:88,nat:"Portugal"},
      {name:"İlkay Gündoğan",pos:"CM",age:33,ovr:84,nat:"Alemania"},
      {name:"Matheus Nunes",pos:"CM",age:26,ovr:79,nat:"Portugal"},
      {name:"Phil Foden",pos:"CAM",age:24,ovr:89,nat:"Inglaterra"},
      {name:"Jack Grealish",pos:"LW",age:28,ovr:83,nat:"Inglaterra"},
      {name:"Jeremy Doku",pos:"LW",age:22,ovr:82,nat:"Bélgica"},
      {name:"Erling Haaland",pos:"ST",age:24,ovr:91,nat:"Noruega"},
      {name:"Julián Álvarez",pos:"ST",age:24,ovr:85,nat:"Argentina"},
      {name:"Savinho",pos:"RW",age:20,ovr:78,nat:"Brasil"},
    ],

    "Manchester United": [
      {name:"André Onana",pos:"GK",age:28,ovr:84,nat:"Camerún"},
      {name:"Tom Heaton",pos:"GK",age:38,ovr:73,nat:"Inglaterra"},
      {name:"Aaron Wan-Bissaka",pos:"RB",age:26,ovr:78,nat:"Congo"},
      {name:"Diogo Dalot",pos:"RB",age:25,ovr:80,nat:"Portugal"},
      {name:"Raphaël Varane",pos:"CB",age:31,ovr:83,nat:"Francia"},
      {name:"Victor Lindelöf",pos:"CB",age:30,ovr:79,nat:"Suecia"},
      {name:"Harry Maguire",pos:"CB",age:31,ovr:78,nat:"Inglaterra"},
      {name:"Leny Yoro",pos:"CB",age:18,ovr:77,nat:"Francia"},
      {name:"Luke Shaw",pos:"LB",age:29,ovr:82,nat:"Inglaterra"},
      {name:"Tyrell Malacia",pos:"LB",age:24,ovr:76,nat:"Países Bajos"},
      {name:"Casemiro",pos:"CDM",age:32,ovr:84,nat:"Brasil"},
      {name:"Sofyan Amrabat",pos:"CDM",age:27,ovr:78,nat:"Marruecos"},
      {name:"Bruno Fernandes",pos:"CAM",age:29,ovr:87,nat:"Portugal"},
      {name:"Christian Eriksen",pos:"CM",age:32,ovr:80,nat:"Dinamarca"},
      {name:"Mason Mount",pos:"CM",age:25,ovr:79,nat:"Inglaterra"},
      {name:"Antony",pos:"RW",age:24,ovr:78,nat:"Brasil"},
      {name:"Marcus Rashford",pos:"LW",age:26,ovr:83,nat:"Inglaterra"},
      {name:"Alejandro Garnacho",pos:"LW",age:20,ovr:78,nat:"Argentina"},
      {name:"Rasmus Højlund",pos:"ST",age:21,ovr:79,nat:"Dinamarca"},
      {name:"Scott McTominay",pos:"CM",age:27,ovr:78,nat:"Escocia"},
    ],

    "Newcastle United": [
      {name:"Nick Pope",pos:"GK",age:32,ovr:84,nat:"Inglaterra"},
      {name:"Martin Dúbravka",pos:"GK",age:35,ovr:77,nat:"Eslovaquia"},
      {name:"Kieran Trippier",pos:"RB",age:33,ovr:84,nat:"Inglaterra"},
      {name:"Tino Livramento",pos:"RB",age:21,ovr:76,nat:"Inglaterra"},
      {name:"Sven Botman",pos:"CB",age:24,ovr:81,nat:"Países Bajos"},
      {name:"Fabian Schär",pos:"CB",age:32,ovr:79,nat:"Suiza"},
      {name:"Dan Burn",pos:"CB",age:32,ovr:77,nat:"Inglaterra"},
      {name:"Matt Targett",pos:"LB",age:28,ovr:75,nat:"Inglaterra"},
      {name:"Lloyd Kelly",pos:"CB",age:25,ovr:76,nat:"Inglaterra"},
      {name:"Joelinton",pos:"CM",age:28,ovr:80,nat:"Brasil"},
      {name:"Bruno Guimarães",pos:"CDM",age:26,ovr:86,nat:"Brasil"},
      {name:"Sandro Tonali",pos:"CM",age:24,ovr:83,nat:"Italia"},
      {name:"Joe Willock",pos:"CM",age:24,ovr:76,nat:"Inglaterra"},
      {name:"Jacob Murphy",pos:"RM",age:29,ovr:75,nat:"Inglaterra"},
      {name:"Harvey Barnes",pos:"LW",age:26,ovr:78,nat:"Inglaterra"},
      {name:"Anthony Gordon",pos:"LW",age:23,ovr:81,nat:"Inglaterra"},
      {name:"Alexander Isak",pos:"ST",age:24,ovr:86,nat:"Suecia"},
      {name:"Callum Wilson",pos:"ST",age:32,ovr:78,nat:"Inglaterra"},
      {name:"Miguel Almirón",pos:"CAM",age:30,ovr:76,nat:"Paraguay"},
    ],

    "Nottingham Forest": [
      {name:"Matt Turner",pos:"GK",age:30,ovr:76,nat:"Estados Unidos"},
      {name:"Odysseas Vlachodimos",pos:"GK",age:30,ovr:78,nat:"Grecia"},
      {name:"Neco Williams",pos:"RB",age:23,ovr:76,nat:"Gales"},
      {name:"Serge Aurier",pos:"RB",age:31,ovr:74,nat:"Costa de Marfil"},
      {name:"Willy Boly",pos:"CB",age:33,ovr:76,nat:"Costa de Marfil"},
      {name:"Joe Worrall",pos:"CB",age:27,ovr:75,nat:"Inglaterra"},
      {name:"Moussa Niakhate",pos:"CB",age:28,ovr:76,nat:"Francia"},
      {name:"Harry Toffolo",pos:"LB",age:28,ovr:74,nat:"Inglaterra"},
      {name:"Ola Aina",pos:"RB",age:27,ovr:75,nat:"Nigeria"},
      {name:"Danilo",pos:"CDM",age:22,ovr:76,nat:"Brasil"},
      {name:"Ryan Yates",pos:"CM",age:26,ovr:74,nat:"Inglaterra"},
      {name:"Morgan Gibbs-White",pos:"CAM",age:24,ovr:79,nat:"Inglaterra"},
      {name:"Anthony Elanga",pos:"RW",age:22,ovr:75,nat:"Suecia"},
      {name:"Callum Hudson-Odoi",pos:"LW",age:23,ovr:75,nat:"Inglaterra"},
      {name:"Chris Wood",pos:"ST",age:32,ovr:76,nat:"Nueva Zelanda"},
      {name:"Taiwo Awoniyi",pos:"ST",age:26,ovr:74,nat:"Nigeria"},
      {name:"Nicolás Domínguez",pos:"CM",age:26,ovr:74,nat:"Argentina"},
      {name:"Divock Origi",pos:"ST",age:29,ovr:73,nat:"Bélgica"},
    ],

    "Sunderland": [
      {name:"Anthony Patterson",pos:"GK",age:23,ovr:72,nat:"Inglaterra"},
      {name:"Edouard Michut",pos:"CM",age:22,ovr:71,nat:"Francia"},
      {name:"Trai Hume",pos:"RB",age:22,ovr:70,nat:"Irlanda del Norte"},
      {name:"Danny Batth",pos:"CB",age:33,ovr:71,nat:"Inglaterra"},
      {name:"Luke O'Nien",pos:"CB",age:29,ovr:72,nat:"Inglaterra"},
      {name:"Dennis Cirkin",pos:"LB",age:22,ovr:72,nat:"Inglaterra"},
      {name:"Dan Neil",pos:"CM",age:22,ovr:72,nat:"Inglaterra"},
      {name:"Corry Evans",pos:"CDM",age:33,ovr:70,nat:"Irlanda del Norte"},
      {name:"Patrick Roberts",pos:"RW",age:27,ovr:72,nat:"Inglaterra"},
      {name:"Bradley Dack",pos:"CAM",age:30,ovr:71,nat:"Inglaterra"},
      {name:"Jack Clarke",pos:"LW",age:23,ovr:74,nat:"Inglaterra"},
      {name:"Ross Stewart",pos:"ST",age:28,ovr:73,nat:"Escocia"},
      {name:"Ellis Simms",pos:"ST",age:23,ovr:72,nat:"Inglaterra"},
      {name:"Amad Diallo",pos:"RW",age:22,ovr:74,nat:"Costa de Marfil"},
      {name:"Chris Rigg",pos:"CM",age:17,ovr:70,nat:"Inglaterra"},
      {name:"Abdoullah Ba",pos:"LW",age:21,ovr:69,nat:"Francia"},
    ],

    "Tottenham Hotspur": [
      {name:"Guglielmo Vicario",pos:"GK",age:28,ovr:82,nat:"Italia"},
      {name:"Fraser Forster",pos:"GK",age:36,ovr:74,nat:"Inglaterra"},
      {name:"Pedro Porro",pos:"RB",age:24,ovr:81,nat:"España"},
      {name:"Emerson Royal",pos:"RB",age:25,ovr:76,nat:"Brasil"},
      {name:"Cristian Romero",pos:"CB",age:26,ovr:86,nat:"Argentina"},
      {name:"Micky van de Ven",pos:"CB",age:23,ovr:82,nat:"Países Bajos"},
      {name:"Ben Davies",pos:"CB",age:31,ovr:77,nat:"Gales"},
      {name:"Destiny Udogie",pos:"LB",age:22,ovr:80,nat:"Italia"},
      {name:"Ivan Perisic",pos:"LB",age:35,ovr:76,nat:"Croacia"},
      {name:"Yves Bissouma",pos:"CDM",age:28,ovr:81,nat:"Malí"},
      {name:"Pape Matar Sarr",pos:"CM",age:22,ovr:78,nat:"Senegal"},
      {name:"James Maddison",pos:"CAM",age:27,ovr:84,nat:"Inglaterra"},
      {name:"Lucas Bergvall",pos:"CM",age:18,ovr:73,nat:"Suecia"},
      {name:"Dejan Kulusevski",pos:"RW",age:24,ovr:83,nat:"Suecia"},
      {name:"Son Heung-min",pos:"LW",age:32,ovr:87,nat:"Corea del Sur"},
      {name:"Brennan Johnson",pos:"RW",age:23,ovr:77,nat:"Gales"},
      {name:"Richarlison",pos:"ST",age:27,ovr:81,nat:"Brasil"},
      {name:"Rodrigo Bentancur",pos:"CM",age:27,ovr:80,nat:"Uruguay"},
      {name:"Timo Werner",pos:"LW",age:28,ovr:76,nat:"Alemania"},
      {name:"Mathys Tel",pos:"ST",age:19,ovr:76,nat:"Francia"},
    ],

    "West Ham United": [
      {name:"Alphonse Areola",pos:"GK",age:31,ovr:79,nat:"Francia"},
      {name:"Lukasz Fabianski",pos:"GK",age:39,ovr:74,nat:"Polonia"},
      {name:"Ben Johnson",pos:"RB",age:24,ovr:74,nat:"Inglaterra"},
      {name:"Vladimir Coufal",pos:"RB",age:32,ovr:76,nat:"República Checa"},
      {name:"Angelo Ogbonna",pos:"CB",age:36,ovr:74,nat:"Italia"},
      {name:"Nayef Aguerd",pos:"CB",age:28,ovr:79,nat:"Marruecos"},
      {name:"Kurt Zouma",pos:"CB",age:29,ovr:78,nat:"Francia"},
      {name:"Emerson Palmieri",pos:"LB",age:29,ovr:77,nat:"Italia"},
      {name:"Aaron Cresswell",pos:"LB",age:34,ovr:74,nat:"Inglaterra"},
      {name:"Edson Álvarez",pos:"CDM",age:26,ovr:82,nat:"México"},
      {name:"Tomáš Souček",pos:"CM",age:29,ovr:79,nat:"República Checa"},
      {name:"James Ward-Prowse",pos:"CM",age:29,ovr:80,nat:"Inglaterra"},
      {name:"Lucas Paquetá",pos:"CAM",age:26,ovr:82,nat:"Brasil"},
      {name:"Jarrod Bowen",pos:"RW",age:27,ovr:82,nat:"Inglaterra"},
      {name:"Mohammed Kudus",pos:"RW",age:23,ovr:79,nat:"Ghana"},
      {name:"Said Benrahma",pos:"LW",age:29,ovr:77,nat:"Argelia"},
      {name:"Michail Antonio",pos:"ST",age:34,ovr:76,nat:"Jamaica"},
      {name:"Danny Ings",pos:"ST",age:32,ovr:75,nat:"Inglaterra"},
    ],

    "Wolverhampton Wanderers": [
      {name:"José Sá",pos:"GK",age:31,ovr:82,nat:"Portugal"},
      {name:"Daniel Bentley",pos:"GK",age:30,ovr:74,nat:"Inglaterra"},
      {name:"Nélson Semedo",pos:"RB",age:30,ovr:80,nat:"Portugal"},
      {name:"Toti Gomes",pos:"CB",age:25,ovr:74,nat:"Portugal"},
      {name:"Craig Dawson",pos:"CB",age:34,ovr:74,nat:"Inglaterra"},
      {name:"Max Kilman",pos:"CB",age:27,ovr:78,nat:"Inglaterra"},
      {name:"Hugo Bueno",pos:"LB",age:22,ovr:73,nat:"España"},
      {name:"Rayan Aït-Nouri",pos:"LB",age:23,ovr:78,nat:"Argelia"},
      {name:"Mario Lemina",pos:"CDM",age:30,ovr:78,nat:"Gabón"},
      {name:"João Gomes",pos:"CDM",age:23,ovr:78,nat:"Brasil"},
      {name:"Tommy Doyle",pos:"CM",age:22,ovr:73,nat:"Inglaterra"},
      {name:"Boubacar Traoré",pos:"CM",age:23,ovr:73,nat:"Malí"},
      {name:"Pablo Sarabia",pos:"CAM",age:32,ovr:78,nat:"España"},
      {name:"Pedro Neto",pos:"RW",age:24,ovr:81,nat:"Portugal"},
      {name:"Hwang Hee-chan",pos:"LW",age:28,ovr:77,nat:"Corea del Sur"},
      {name:"Matheus Cunha",pos:"ST",age:25,ovr:81,nat:"Brasil"},
      {name:"Sasa Kalajdzic",pos:"ST",age:27,ovr:74,nat:"Austria"},
      {name:"Ennis Sari",pos:"LW",age:23,ovr:70,nat:"Francia"},
    ],

    /* ===== BUNDESLIGA ===== */

    "Bayern Múnich": [
      {name:"Manuel Neuer",pos:"GK",age:38,ovr:87,nat:"Alemania"},
      {name:"Sven Ulreich",pos:"GK",age:36,ovr:76,nat:"Alemania"},
      {name:"Noussair Mazraoui",pos:"RB",age:26,ovr:80,nat:"Marruecos"},
      {name:"Josip Stanisic",pos:"RB",age:24,ovr:74,nat:"Croacia"},
      {name:"Kim Min-jae",pos:"CB",age:28,ovr:86,nat:"Corea del Sur"},
      {name:"Dayot Upamecano",pos:"CB",age:25,ovr:84,nat:"Francia"},
      {name:"Matthijs de Ligt",pos:"CB",age:25,ovr:82,nat:"Países Bajos"},
      {name:"Alphonso Davies",pos:"LB",age:23,ovr:85,nat:"Canadá"},
      {name:"João Palhinha",pos:"CDM",age:28,ovr:83,nat:"Portugal"},
      {name:"Leon Goretzka",pos:"CM",age:29,ovr:83,nat:"Alemania"},
      {name:"Joshua Kimmich",pos:"CM",age:29,ovr:88,nat:"Alemania"},
      {name:"Leroy Sané",pos:"RW",age:28,ovr:86,nat:"Alemania"},
      {name:"Serge Gnabry",pos:"RW",age:29,ovr:83,nat:"Alemania"},
      {name:"Thomas Müller",pos:"CAM",age:34,ovr:83,nat:"Alemania"},
      {name:"Jamal Musiala",pos:"CAM",age:21,ovr:88,nat:"Alemania"},
      {name:"Michael Olise",pos:"RW",age:22,ovr:82,nat:"Francia"},
      {name:"Kingsley Coman",pos:"LW",age:28,ovr:84,nat:"Francia"},
      {name:"Harry Kane",pos:"ST",age:31,ovr:90,nat:"Inglaterra"},
      {name:"Eric Maxim Choupo-Moting",pos:"ST",age:35,ovr:76,nat:"Camerún"},
      {name:"Raphaël Guerreiro",pos:"LB",age:30,ovr:80,nat:"Portugal"},
    ],

    "Borussia Dortmund": [
      {name:"Gregor Kobel",pos:"GK",age:26,ovr:83,nat:"Suiza"},
      {name:"Alexander Meyer",pos:"GK",age:32,ovr:74,nat:"Alemania"},
      {name:"Julian Ryerson",pos:"RB",age:27,ovr:76,nat:"Noruega"},
      {name:"Mats Hummels",pos:"CB",age:35,ovr:82,nat:"Alemania"},
      {name:"Niklas Süle",pos:"CB",age:28,ovr:81,nat:"Alemania"},
      {name:"Nico Schlotterbeck",pos:"CB",age:24,ovr:81,nat:"Alemania"},
      {name:"Ramy Bensebaini",pos:"LB",age:29,ovr:79,nat:"Argelia"},
      {name:"Ian Maatsen",pos:"LB",age:22,ovr:78,nat:"Países Bajos"},
      {name:"Emre Can",pos:"CDM",age:30,ovr:79,nat:"Alemania"},
      {name:"Marcel Sabitzer",pos:"CM",age:30,ovr:80,nat:"Austria"},
      {name:"Felix Nmecha",pos:"CM",age:23,ovr:77,nat:"Alemania"},
      {name:"Karim Adeyemi",pos:"LW",age:22,ovr:80,nat:"Alemania"},
      {name:"Jamie Gittens",pos:"LW",age:20,ovr:76,nat:"Inglaterra"},
      {name:"Donyell Malen",pos:"RW",age:25,ovr:79,nat:"Países Bajos"},
      {name:"Julian Brandt",pos:"CAM",age:28,ovr:82,nat:"Alemania"},
      {name:"Marco Reus",pos:"CAM",age:35,ovr:80,nat:"Alemania"},
      {name:"Sébastien Haller",pos:"ST",age:30,ovr:78,nat:"Costa de Marfil"},
      {name:"Niclas Füllkrug",pos:"ST",age:31,ovr:81,nat:"Alemania"},
      {name:"Giovanni Reyna",pos:"CAM",age:21,ovr:75,nat:"Estados Unidos"},
    ],

    "RB Leipzig": [
      {name:"Peter Gulácsi",pos:"GK",age:34,ovr:82,nat:"Hungría"},
      {name:"Janis Blaswich",pos:"GK",age:33,ovr:76,nat:"Alemania"},
      {name:"Benjamin Henrichs",pos:"RB",age:27,ovr:78,nat:"Alemania"},
      {name:"Willi Orban",pos:"CB",age:31,ovr:78,nat:"Hungría"},
      {name:"Mohamed Simakan",pos:"CB",age:24,ovr:79,nat:"Francia"},
      {name:"Castello Lukeba",pos:"CB",age:21,ovr:80,nat:"Francia"},
      {name:"David Raum",pos:"LB",age:26,ovr:80,nat:"Alemania"},
      {name:"Christoph Baumgartner",pos:"CAM",age:25,ovr:78,nat:"Austria"},
      {name:"Nicolas Seiwald",pos:"CDM",age:23,ovr:77,nat:"Austria"},
      {name:"Xavi Simons",pos:"CAM",age:21,ovr:81,nat:"Países Bajos"},
      {name:"Kevin Kampl",pos:"CDM",age:33,ovr:77,nat:"Eslovenia"},
      {name:"Amadou Haidara",pos:"CM",age:26,ovr:78,nat:"Malí"},
      {name:"Lois Openda",pos:"ST",age:24,ovr:82,nat:"Bélgica"},
      {name:"Benjamin Šeško",pos:"ST",age:21,ovr:81,nat:"Eslovenia"},
      {name:"Timo Werner",pos:"LW",age:28,ovr:79,nat:"Alemania"},
      {name:"Assan Ouédraogo",pos:"CM",age:18,ovr:71,nat:"Alemania"},
      {name:"Yussuf Poulsen",pos:"ST",age:30,ovr:74,nat:"Dinamarca"},
      {name:"Emil Forsberg",pos:"CAM",age:32,ovr:78,nat:"Suecia"},
    ],

    "Bayer Leverkusen": [
      {name:"Lukáš Hrádecký",pos:"GK",age:34,ovr:82,nat:"Finlandia"},
      {name:"Matej Kovár",pos:"GK",age:24,ovr:78,nat:"República Checa"},
      {name:"Jeremie Frimpong",pos:"RB",age:23,ovr:82,nat:"Países Bajos"},
      {name:"Piero Hincapié",pos:"LB",age:22,ovr:79,nat:"Ecuador"},
      {name:"Jonathan Tah",pos:"CB",age:28,ovr:83,nat:"Alemania"},
      {name:"Edmond Tapsoba",pos:"CB",age:25,ovr:80,nat:"Burkina Faso"},
      {name:"Odilon Kossounou",pos:"CB",age:24,ovr:77,nat:"Costa de Marfil"},
      {name:"Alejandro Grimaldo",pos:"LB",age:28,ovr:84,nat:"España"},
      {name:"Granit Xhaka",pos:"CDM",age:31,ovr:84,nat:"Suiza"},
      {name:"Robert Andrich",pos:"CDM",age:29,ovr:80,nat:"Alemania"},
      {name:"Exequiel Palacios",pos:"CM",age:26,ovr:79,nat:"Argentina"},
      {name:"Florian Wirtz",pos:"CAM",age:21,ovr:88,nat:"Alemania"},
      {name:"Jonas Hofmann",pos:"RW",age:32,ovr:79,nat:"Alemania"},
      {name:"Amine Adli",pos:"LW",age:24,ovr:77,nat:"Marruecos"},
      {name:"Adam Hlozek",pos:"RW",age:22,ovr:76,nat:"República Checa"},
      {name:"Patrik Schick",pos:"ST",age:28,ovr:82,nat:"República Checa"},
      {name:"Victor Boniface",pos:"ST",age:23,ovr:82,nat:"Nigeria"},
      {name:"Nathan Tella",pos:"LW",age:24,ovr:74,nat:"Nigeria"},
    ],

    "Eintracht Frankfurt": [
      {name:"Kevin Trapp",pos:"GK",age:34,ovr:82,nat:"Alemania"},
      {name:"Kaua Santos",pos:"GK",age:21,ovr:70,nat:"Brasil"},
      {name:"Kristijan Jakic",pos:"CM",age:27,ovr:74,nat:"Croacia"},
      {name:"Tuta",pos:"CB",age:25,ovr:77,nat:"Brasil"},
      {name:"Robin Koch",pos:"CB",age:28,ovr:78,nat:"Alemania"},
      {name:"Willian Pacho",pos:"CB",age:22,ovr:78,nat:"Ecuador"},
      {name:"Philipp Max",pos:"LB",age:30,ovr:76,nat:"Alemania"},
      {name:"Aurelio Buta",pos:"RB",age:27,ovr:74,nat:"Portugal"},
      {name:"Ellyes Skhiri",pos:"CDM",age:29,ovr:78,nat:"Túnez"},
      {name:"Hugo Larsson",pos:"CM",age:20,ovr:74,nat:"Suecia"},
      {name:"Farès Chaibi",pos:"CAM",age:22,ovr:75,nat:"Francia"},
      {name:"Junior Dina Ebimbe",pos:"CM",age:23,ovr:74,nat:"Francia"},
      {name:"Ansgar Knauff",pos:"RW",age:22,ovr:73,nat:"Alemania"},
      {name:"Jesper Lindström",pos:"RW",age:24,ovr:76,nat:"Dinamarca"},
      {name:"Faride Abubakar",pos:"LW",age:21,ovr:71,nat:"Alemania"},
      {name:"Omar Marmoush",pos:"ST",age:25,ovr:81,nat:"Egipto"},
      {name:"Randal Kolo Muani",pos:"ST",age:25,ovr:82,nat:"Francia"},
      {name:"Nathaniel Brown",pos:"RB",age:20,ovr:70,nat:"Alemania"},
    ],

    "VfB Stuttgart": [
      {name:"Alexander Nübel",pos:"GK",age:28,ovr:80,nat:"Alemania"},
      {name:"Fabian Bredlow",pos:"GK",age:29,ovr:73,nat:"Alemania"},
      {name:"Pascal Stenzel",pos:"RB",age:28,ovr:74,nat:"Alemania"},
      {name:"Josha Vagnoman",pos:"RB",age:24,ovr:74,nat:"Alemania"},
      {name:"Hiroki Ito",pos:"CB",age:25,ovr:78,nat:"Japón"},
      {name:"Waldemar Anton",pos:"CB",age:27,ovr:78,nat:"Alemania"},
      {name:"Dan-Axel Zagadou",pos:"CB",age:25,ovr:76,nat:"Francia"},
      {name:"Maximilian Mittelstädt",pos:"LB",age:27,ovr:78,nat:"Alemania"},
      {name:"Angelo Stiller",pos:"CDM",age:23,ovr:76,nat:"Alemania"},
      {name:"Atakan Karazor",pos:"CDM",age:27,ovr:74,nat:"Turquía"},
      {name:"Enzo Millot",pos:"CM",age:23,ovr:74,nat:"Francia"},
      {name:"Jamie Leweling",pos:"LW",age:23,ovr:74,nat:"Alemania"},
      {name:"Silas Katompa",pos:"RW",age:25,ovr:73,nat:"Congo"},
      {name:"Chris Führich",pos:"LW",age:26,ovr:76,nat:"Alemania"},
      {name:"Deniz Undav",pos:"ST",age:28,ovr:79,nat:"Alemania"},
      {name:"Serhou Guirassy",pos:"ST",age:28,ovr:83,nat:"Guinea"},
      {name:"Ermedin Demirovic",pos:"ST",age:26,ovr:77,nat:"Bosnia"},
    ],

    "SC Freiburg": [
      {name:"Noah Atubolu",pos:"GK",age:22,ovr:74,nat:"Alemania"},
      {name:"Mark Flekken",pos:"GK",age:31,ovr:80,nat:"Países Bajos"},
      {name:"Lukas Kübler",pos:"RB",age:31,ovr:73,nat:"Alemania"},
      {name:"Kiliann Sildillia",pos:"RB",age:21,ovr:73,nat:"Francia"},
      {name:"Manuel Gulde",pos:"CB",age:33,ovr:73,nat:"Alemania"},
      {name:"Matthias Ginter",pos:"CB",age:30,ovr:78,nat:"Alemania"},
      {name:"Philipp Lienhart",pos:"CB",age:28,ovr:75,nat:"Austria"},
      {name:"Christian Günter",pos:"LB",age:31,ovr:77,nat:"Alemania"},
      {name:"Nicolas Höfler",pos:"CDM",age:32,ovr:73,nat:"Alemania"},
      {name:"Maximilian Eggestein",pos:"CM",age:27,ovr:73,nat:"Alemania"},
      {name:"Yannik Keitel",pos:"CM",age:23,ovr:72,nat:"Alemania"},
      {name:"Ritsu Doan",pos:"RW",age:26,ovr:77,nat:"Japón"},
      {name:"Jonathan Schmid",pos:"RM",age:33,ovr:72,nat:"Francia"},
      {name:"Vincenzo Grifo",pos:"LW",age:31,ovr:77,nat:"Italia"},
      {name:"Michael Gregoritsch",pos:"ST",age:30,ovr:75,nat:"Austria"},
      {name:"Lucas Höler",pos:"ST",age:30,ovr:73,nat:"Alemania"},
      {name:"Junior Adamu",pos:"ST",age:23,ovr:72,nat:"Austria"},
    ],

    "Werder Bremen": [
      {name:"Jiri Pavlenka",pos:"GK",age:32,ovr:76,nat:"República Checa"},
      {name:"Michael Zetterer",pos:"GK",age:29,ovr:73,nat:"Alemania"},
      {name:"Thomas Ododoru",pos:"RB",age:25,ovr:71,nat:"Alemania"},
      {name:"Milos Veljkovic",pos:"CB",age:29,ovr:75,nat:"Serbia"},
      {name:"Niklas Stark",pos:"CB",age:29,ovr:75,nat:"Alemania"},
      {name:"Marco Friedl",pos:"CB",age:25,ovr:74,nat:"Austria"},
      {name:"Amos Pieper",pos:"CB",age:27,ovr:73,nat:"Alemania"},
      {name:"Omer Faruk Beyaz",pos:"CAM",age:21,ovr:71,nat:"Turquía"},
      {name:"Christian Groß",pos:"CDM",age:36,ovr:72,nat:"Alemania"},
      {name:"Leonardo Bittencourt",pos:"CAM",age:30,ovr:73,nat:"Brasil"},
      {name:"Romano Schmid",pos:"CM",age:24,ovr:72,nat:"Austria"},
      {name:"Mitchell Weiser",pos:"RM",age:30,ovr:73,nat:"Alemania"},
      {name:"Dawid Kownacki",pos:"LW",age:27,ovr:71,nat:"Polonia"},
      {name:"Niclas Füllkrug",pos:"ST",age:31,ovr:81,nat:"Alemania"},
      {name:"Marvin Ducksch",pos:"ST",age:30,ovr:75,nat:"Alemania"},
      {name:"Oliver Burke",pos:"RW",age:27,ovr:70,nat:"Escocia"},
      {name:"Felix Agu",pos:"LB",age:24,ovr:71,nat:"Alemania"},
    ],

    "FC Augsburg": [
      {name:"Finn Dahmen",pos:"GK",age:26,ovr:73,nat:"Alemania"},
      {name:"Tomas Koubek",pos:"GK",age:32,ovr:73,nat:"República Checa"},
      {name:"Ruben Vargas",pos:"LW",age:25,ovr:74,nat:"Suiza"},
      {name:"Raphael Framberger",pos:"RB",age:28,ovr:72,nat:"Alemania"},
      {name:"Robert Gumny",pos:"RB",age:26,ovr:71,nat:"Polonia"},
      {name:"Jeffrey Gouweleeuw",pos:"CB",age:32,ovr:74,nat:"Países Bajos"},
      {name:"Felix Uduokhai",pos:"CB",age:27,ovr:73,nat:"Alemania"},
      {name:"Philipp Tietz",pos:"ST",age:25,ovr:72,nat:"Alemania"},
      {name:"Mads Pedersen",pos:"LB",age:27,ovr:74,nat:"Dinamarca"},
      {name:"Elvis Rexhbecaj",pos:"CM",age:26,ovr:72,nat:"Alemania"},
      {name:"Niklas Dorsch",pos:"CDM",age:26,ovr:73,nat:"Alemania"},
      {name:"Arne Maier",pos:"CM",age:25,ovr:73,nat:"Alemania"},
      {name:"Fredrik Jensen",pos:"RM",age:27,ovr:72,nat:"Finlandia"},
      {name:"Alexis Claude-Maurice",pos:"LW",age:26,ovr:71,nat:"Francia"},
      {name:"Samuel Essende",pos:"ST",age:26,ovr:70,nat:"Francia"},
      {name:"Ermedin Demirovic",pos:"ST",age:26,ovr:76,nat:"Bosnia"},
      {name:"Mergim Berisha",pos:"ST",age:25,ovr:73,nat:"Kosovo"},
    ],

    "VfL Wolfsburg": [
      {name:"Koen Casteels",pos:"GK",age:32,ovr:82,nat:"Bélgica"},
      {name:"Pavao Pervan",pos:"GK",age:36,ovr:72,nat:"Austria"},
      {name:"Ridle Baku",pos:"RB",age:26,ovr:77,nat:"Alemania"},
      {name:"Sebastian Röthlisberger",pos:"RB",age:28,ovr:71,nat:"Suiza"},
      {name:"Maxence Lacroix",pos:"CB",age:24,ovr:77,nat:"Francia"},
      {name:"Sebastiaan Bornauw",pos:"CB",age:25,ovr:75,nat:"Bélgica"},
      {name:"Kevin Behrens",pos:"ST",age:33,ovr:72,nat:"Alemania"},
      {name:"Paulo Otavio",pos:"LB",age:30,ovr:74,nat:"Brasil"},
      {name:"Joakim Maehle",pos:"LB",age:27,ovr:76,nat:"Dinamarca"},
      {name:"Mattias Svanberg",pos:"CM",age:25,ovr:74,nat:"Suecia"},
      {name:"Maximilian Arnold",pos:"CDM",age:29,ovr:78,nat:"Alemania"},
      {name:"Yannick Gerhardt",pos:"CM",age:30,ovr:73,nat:"Alemania"},
      {name:"Patrick Wimmer",pos:"LM",age:23,ovr:73,nat:"Austria"},
      {name:"Jakub Kaminski",pos:"LW",age:22,ovr:73,nat:"Polonia"},
      {name:"Lukas Nmecha",pos:"ST",age:25,ovr:76,nat:"Alemania"},
      {name:"Jonas Wind",pos:"ST",age:25,ovr:75,nat:"Dinamarca"},
      {name:"Tiago Tomás",pos:"ST",age:23,ovr:74,nat:"Portugal"},
    ],

    "Borussia Mönchengladbach": [
      {name:"Jonas Omlin",pos:"GK",age:30,ovr:78,nat:"Suiza"},
      {name:"Tobias Sippel",pos:"GK",age:36,ovr:72,nat:"Alemania"},
      {name:"Stefan Lainer",pos:"RB",age:32,ovr:74,nat:"Austria"},
      {name:"Joe Scally",pos:"RB",age:21,ovr:74,nat:"Estados Unidos"},
      {name:"Nico Elvedi",pos:"CB",age:27,ovr:78,nat:"Suiza"},
      {name:"Marvin Friedrich",pos:"CB",age:28,ovr:74,nat:"Alemania"},
      {name:"Ko Itakura",pos:"CB",age:27,ovr:76,nat:"Japón"},
      {name:"Ramy Bensebaini",pos:"LB",age:29,ovr:78,nat:"Argelia"},
      {name:"Florian Neuhaus",pos:"CM",age:27,ovr:76,nat:"Alemania"},
      {name:"Manu Koné",pos:"CDM",age:23,ovr:77,nat:"Francia"},
      {name:"Julian Weigl",pos:"CDM",age:28,ovr:76,nat:"Alemania"},
      {name:"Patrick Herrmann",pos:"RM",age:33,ovr:72,nat:"Alemania"},
      {name:"Alassane Pléa",pos:"ST",age:31,ovr:76,nat:"Francia"},
      {name:"Jonas Hofmann",pos:"RW",age:31,ovr:78,nat:"Alemania"},
      {name:"Marcus Thuram",pos:"ST",age:26,ovr:82,nat:"Francia"},
      {name:"Lars Stindl",pos:"CAM",age:35,ovr:72,nat:"Alemania"},
      {name:"Franck Honorat",pos:"RW",age:26,ovr:73,nat:"Francia"},
    ],

    "Mainz 05": [
      {name:"Robin Zentner",pos:"GK",age:29,ovr:76,nat:"Alemania"},
      {name:"Finn Dahmen",pos:"GK",age:26,ovr:73,nat:"Alemania"},
      {name:"Stefan Bell",pos:"CB",age:32,ovr:74,nat:"Alemania"},
      {name:"Andreas Hanche-Olsen",pos:"CB",age:27,ovr:73,nat:"Noruega"},
      {name:"Edimilson Fernandes",pos:"CM",age:28,ovr:73,nat:"Suiza"},
      {name:"Silvan Widmer",pos:"RB",age:31,ovr:74,nat:"Suiza"},
      {name:"Philipp Mwene",pos:"LB",age:30,ovr:72,nat:"Austria"},
      {name:"Maxim Leitsch",pos:"CB",age:25,ovr:72,nat:"Alemania"},
      {name:"Anton Stach",pos:"CM",age:26,ovr:74,nat:"Alemania"},
      {name:"Dominik Kohr",pos:"CDM",age:30,ovr:73,nat:"Alemania"},
      {name:"Leandro Barreiro",pos:"CM",age:24,ovr:74,nat:"Luxemburgo"},
      {name:"Danny da Costa",pos:"RB",age:30,ovr:72,nat:"Alemania"},
      {name:"Karim Onisiwo",pos:"LW",age:31,ovr:73,nat:"Austria"},
      {name:"Aymen Barkok",pos:"CAM",age:26,ovr:72,nat:"Marruecos"},
      {name:"Jonathan Burkardt",pos:"ST",age:23,ovr:77,nat:"Alemania"},
      {name:"Ludovic Ajorque",pos:"ST",age:29,ovr:74,nat:"Francia"},
      {name:"Marcus Ingvartsen",pos:"ST",age:28,ovr:72,nat:"Dinamarca"},
    ],

    "Union Berlin": [
      {name:"Frederik Rönnow",pos:"GK",age:31,ovr:76,nat:"Dinamarca"},
      {name:"Lennart Grill",pos:"GK",age:24,ovr:71,nat:"Alemania"},
      {name:"Julian Ryerson",pos:"RB",age:27,ovr:75,nat:"Noruega"},
      {name:"Timo Baumgartl",pos:"CB",age:27,ovr:73,nat:"Alemania"},
      {name:"Danilho Doekhi",pos:"CB",age:25,ovr:75,nat:"Países Bajos"},
      {name:"Robin Knoche",pos:"CB",age:31,ovr:74,nat:"Alemania"},
      {name:"Josip Juranovic",pos:"RB",age:28,ovr:75,nat:"Croacia"},
      {name:"Diogo Leite",pos:"CB",age:24,ovr:74,nat:"Portugal"},
      {name:"Aïssa Laïdouni",pos:"CDM",age:27,ovr:73,nat:"Túnez"},
      {name:"Rani Khedira",pos:"CM",age:30,ovr:73,nat:"Alemania"},
      {name:"Alex Kral",pos:"CM",age:26,ovr:73,nat:"República Checa"},
      {name:"Sheraldo Becker",pos:"LW",age:28,ovr:76,nat:"Países Bajos"},
      {name:"Kevin Behrens",pos:"ST",age:33,ovr:73,nat:"Alemania"},
      {name:"Jordan Siebatcheu",pos:"ST",age:27,ovr:73,nat:"Francia"},
      {name:"Benedict Hollerbach",pos:"RW",age:23,ovr:72,nat:"Alemania"},
      {name:"Miloš Pantovic",pos:"CM",age:27,ovr:71,nat:"Serbia"},
      {name:"Jamie Leweling",pos:"LW",age:23,ovr:73,nat:"Alemania"},
    ],

    "TSG Hoffenheim": [
      {name:"Oliver Baumann",pos:"GK",age:34,ovr:77,nat:"Alemania"},
      {name:"Luca Philipp",pos:"GK",age:25,ovr:70,nat:"Alemania"},
      {name:"Pavel Kaderabek",pos:"RB",age:32,ovr:74,nat:"República Checa"},
      {name:"Kevin Vogt",pos:"CB",age:32,ovr:74,nat:"Alemania"},
      {name:"Ozan Kabak",pos:"CB",age:24,ovr:74,nat:"Turquía"},
      {name:"Stanley N'Soki",pos:"LB",age:27,ovr:72,nat:"Francia"},
      {name:"Angelo Stiller",pos:"CDM",age:23,ovr:75,nat:"Alemania"},
      {name:"Dennis Geiger",pos:"CM",age:25,ovr:72,nat:"Alemania"},
      {name:"Sebastian Rudy",pos:"CDM",age:34,ovr:73,nat:"Alemania"},
      {name:"Ihlas Bebou",pos:"LW",age:30,ovr:74,nat:"Togo"},
      {name:"Adam Hlozek",pos:"RW",age:22,ovr:74,nat:"República Checa"},
      {name:"Marius Bülter",pos:"LW",age:30,ovr:73,nat:"Alemania"},
      {name:"Robert Skov",pos:"RM",age:28,ovr:73,nat:"Dinamarca"},
      {name:"Andrej Kramaric",pos:"ST",age:33,ovr:80,nat:"Croacia"},
      {name:"Wout Weghorst",pos:"ST",age:32,ovr:76,nat:"Países Bajos"},
      {name:"Fisayo Dele-Bashiru",pos:"CM",age:23,ovr:72,nat:"Nigeria"},
      {name:"John Brooks",pos:"CB",age:31,ovr:75,nat:"Estados Unidos"},
    ],

    "FC St. Pauli": [
      {name:"Nikola Vasilj",pos:"GK",age:27,ovr:73,nat:"Bosnia"},
      {name:"Sascha Burchert",pos:"GK",age:34,ovr:70,nat:"Alemania"},
      {name:"Manolis Saliakas",pos:"RB",age:27,ovr:71,nat:"Grecia"},
      {name:"Jakov Medic",pos:"CB",age:25,ovr:71,nat:"Croacia"},
      {name:"Karol Mets",pos:"CB",age:30,ovr:70,nat:"Estonia"},
      {name:"Philipp Treu",pos:"LB",age:22,ovr:69,nat:"Alemania"},
      {name:"Leart Paqarada",pos:"LB",age:28,ovr:72,nat:"Kosovo"},
      {name:"Jackson Irvine",pos:"CM",age:31,ovr:72,nat:"Australia"},
      {name:"Carlo Boukhalfa",pos:"CM",age:24,ovr:69,nat:"Alemania"},
      {name:"Eric Smith",pos:"CDM",age:27,ovr:71,nat:"Suecia"},
      {name:"Oladapo Afolabi",pos:"LW",age:24,ovr:70,nat:"Austria"},
      {name:"Elias Saad",pos:"LW",age:24,ovr:71,nat:"Alemania"},
      {name:"Danel Sinani",pos:"CAM",age:27,ovr:72,nat:"Luxemburgo"},
      {name:"Hauke Wahl",pos:"CB",age:30,ovr:70,nat:"Alemania"},
      {name:"Guilherme Ramos",pos:"CB",age:22,ovr:70,nat:"Portugal"},
      {name:"Robert Glatzel",pos:"ST",age:30,ovr:74,nat:"Alemania"},
      {name:"Luca Pfeiffer",pos:"ST",age:27,ovr:70,nat:"Alemania"},
    ],

    "1. FC Heidenheim": [
      {name:"Kevin Müller",pos:"GK",age:32,ovr:72,nat:"Alemania"},
      {name:"Vitus Eicher",pos:"GK",age:21,ovr:67,nat:"Alemania"},
      {name:"Jan Schöppner",pos:"RB",age:26,ovr:69,nat:"Alemania"},
      {name:"Patrick Mainka",pos:"CB",age:28,ovr:70,nat:"Alemania"},
      {name:"Marnon Busch",pos:"CB",age:26,ovr:69,nat:"Alemania"},
      {name:"Benedikt Gimber",pos:"CB",age:29,ovr:70,nat:"Alemania"},
      {name:"Jonas Föhrenbach",pos:"LB",age:25,ovr:69,nat:"Alemania"},
      {name:"Adrian Beck",pos:"RB",age:24,ovr:68,nat:"Alemania"},
      {name:"Tobias Mohr",pos:"LW",age:28,ovr:71,nat:"Alemania"},
      {name:"Jan-Niklas Beste",pos:"LW",age:25,ovr:72,nat:"Alemania"},
      {name:"Denis Thomalla",pos:"ST",age:30,ovr:70,nat:"Alemania"},
      {name:"Marvin Pieringer",pos:"ST",age:24,ovr:69,nat:"Alemania"},
      {name:"Mathias Honsak",pos:"RW",age:27,ovr:71,nat:"Austria"},
      {name:"Sirlord Conteh",pos:"LW",age:24,ovr:69,nat:"Alemania"},
      {name:"Lennard Maloney",pos:"CM",age:24,ovr:69,nat:"Estados Unidos"},
      {name:"Jonas Thimme",pos:"CDM",age:22,ovr:67,nat:"Alemania"},
    ],

    "1. FC Köln": [
      {name:"Marvin Schwäbe",pos:"GK",age:29,ovr:75,nat:"Alemania"},
      {name:"Timo Horn",pos:"GK",age:31,ovr:74,nat:"Alemania"},
      {name:"Benno Schmitz",pos:"RB",age:29,ovr:72,nat:"Alemania"},
      {name:"Luca Kilian",pos:"CB",age:24,ovr:72,nat:"Alemania"},
      {name:"Timo Hübers",pos:"CB",age:27,ovr:73,nat:"Alemania"},
      {name:"Kingsley Ehizibue",pos:"RB",age:28,ovr:71,nat:"Países Bajos"},
      {name:"Charalampos Kostoulas",pos:"CB",age:19,ovr:67,nat:"Grecia"},
      {name:"Jonas Hector",pos:"LB",age:33,ovr:73,nat:"Alemania"},
      {name:"Denis Huseinbasic",pos:"CM",age:22,ovr:70,nat:"Alemania"},
      {name:"Florian Kainz",pos:"LW",age:31,ovr:74,nat:"Austria"},
      {name:"Dejan Ljubicic",pos:"CM",age:26,ovr:73,nat:"Austria"},
      {name:"Damion Downs",pos:"RW",age:21,ovr:68,nat:"Estados Unidos"},
      {name:"Sargis Adamyan",pos:"LW",age:31,ovr:72,nat:"Armenia"},
      {name:"Davie Selke",pos:"ST",age:29,ovr:73,nat:"Alemania"},
      {name:"Steffen Tigges",pos:"ST",age:26,ovr:70,nat:"Alemania"},
      {name:"Mark Uth",pos:"CAM",age:32,ovr:73,nat:"Alemania"},
      {name:"Florian Dietz",pos:"ST",age:25,ovr:71,nat:"Alemania"},
    ],

    "Hamburgo SV": [
      {name:"Daniel Heuer Fernandes",pos:"GK",age:31,ovr:75,nat:"Alemania"},
      {name:"Matheo Raab",pos:"GK",age:24,ovr:70,nat:"Alemania"},
      {name:"Moritz Heyer",pos:"RB",age:28,ovr:72,nat:"Alemania"},
      {name:"Jonas David",pos:"CB",age:24,ovr:72,nat:"Alemania"},
      {name:"Miro Muheim",pos:"LB",age:26,ovr:72,nat:"Suiza"},
      {name:"Sebastian Schonlau",pos:"CB",age:30,ovr:73,nat:"Alemania"},
      {name:"Mario Vuskovic",pos:"CB",age:23,ovr:73,nat:"Croacia"},
      {name:"William Mikelbrencis",pos:"RB",age:20,ovr:70,nat:"Francia"},
      {name:"Ludovit Reis",pos:"CM",age:24,ovr:74,nat:"Países Bajos"},
      {name:"László Bénes",pos:"CM",age:27,ovr:72,nat:"Eslovaquia"},
      {name:"Lukasz Poreba",pos:"CDM",age:24,ovr:70,nat:"Polonia"},
      {name:"Ransford Königsdörfer",pos:"LW",age:22,ovr:71,nat:"Alemania"},
      {name:"Jean-Luc Dompé",pos:"LW",age:28,ovr:72,nat:"Francia"},
      {name:"Faride Abubakar",pos:"RW",age:21,ovr:70,nat:"Alemania"},
      {name:"Robert Glatzel",pos:"ST",age:30,ovr:75,nat:"Alemania"},
      {name:"Bakery Jatta",pos:"LW",age:27,ovr:72,nat:"Gambia"},
      {name:"Noah Katterbach",pos:"LB",age:23,ovr:70,nat:"Alemania"},
    ],

    /* ===== LIGUE 1 ===== */

    "Paris Saint-Germain": [
      {name:"Gianluigi Donnarumma",pos:"GK",age:25,ovr:87,nat:"Italia"},
      {name:"Achraf Hakimi",pos:"RB",age:25,ovr:86,nat:"Marruecos"},
      {name:"Marquinhos",pos:"CB",age:30,ovr:86,nat:"Brasil"},
      {name:"Lucas Hernández",pos:"CB",age:28,ovr:82,nat:"Francia"},
      {name:"Nuno Mendes",pos:"LB",age:22,ovr:84,nat:"Portugal"},
      {name:"Vitinha",pos:"CM",age:24,ovr:85,nat:"Portugal"},
      {name:"Warren Zaïre-Emery",pos:"CM",age:18,ovr:80,nat:"Francia"},
      {name:"Fabián Ruiz",pos:"CM",age:27,ovr:83,nat:"España"},
      {name:"Ousmane Dembélé",pos:"RW",age:27,ovr:87,nat:"Francia"},
      {name:"Bradley Barcola",pos:"LW",age:21,ovr:84,nat:"Francia"},
      {name:"Randal Kolo Muani",pos:"ST",age:25,ovr:84,nat:"Francia"},
      {name:"Marco Asensio",pos:"CAM",age:28,ovr:82,nat:"España"},
      {name:"Gonçalo Ramos",pos:"ST",age:23,ovr:82,nat:"Portugal"},
      {name:"Milan Škriniar",pos:"CB",age:29,ovr:83,nat:"Eslovaquia"},
      {name:"Lee Kang-in",pos:"CAM",age:23,ovr:81,nat:"Corea del Sur"},
      {name:"Matvey Safonov",pos:"GK",age:24,ovr:76,nat:"Rusia"},
    ],
    "Marsella": [
      {name:"Pau López",pos:"GK",age:29,ovr:78,nat:"España"},
      {name:"Jonathan Clauss",pos:"RB",age:31,ovr:78,nat:"Francia"},
      {name:"Samuel Gigot",pos:"CB",age:30,ovr:76,nat:"Francia"},
      {name:"Leonardo Balerdi",pos:"CB",age:25,ovr:78,nat:"Argentina"},
      {name:"Nuno Tavares",pos:"LB",age:23,ovr:77,nat:"Portugal"},
      {name:"Valentin Rongier",pos:"CDM",age:29,ovr:76,nat:"Francia"},
      {name:"Geoffrey Kondogbia",pos:"CDM",age:31,ovr:77,nat:"República Centroafricana"},
      {name:"Azzedine Ounahi",pos:"CM",age:23,ovr:76,nat:"Marruecos"},
      {name:"Iliman Ndiaye",pos:"RW",age:24,ovr:79,nat:"Senegal"},
      {name:"Amine Harit",pos:"CAM",age:27,ovr:77,nat:"Marruecos"},
      {name:"Pierre-Emerick Aubameyang",pos:"ST",age:35,ovr:80,nat:"Gabón"},
      {name:"Ismaïla Sarr",pos:"LW",age:26,ovr:79,nat:"Senegal"},
      {name:"Jordan Veretout",pos:"CM",age:31,ovr:77,nat:"Francia"},
      {name:"Rubén Blanco",pos:"GK",age:28,ovr:74,nat:"España"},
    ],
    "Mónaco": [
      {name:"Radosław Majecki",pos:"GK",age:24,ovr:76,nat:"Polonia"},
      {name:"Vanderson",pos:"RB",age:22,ovr:78,nat:"Brasil"},
      {name:"Axel Disasi",pos:"CB",age:26,ovr:78,nat:"Francia"},
      {name:"Youssouf Fofana",pos:"CDM",age:25,ovr:80,nat:"Francia"},
      {name:"Caio Henrique",pos:"LB",age:26,ovr:80,nat:"Brasil"},
      {name:"Denis Zakaria",pos:"CDM",age:27,ovr:78,nat:"Suiza"},
      {name:"Aleksandr Golovin",pos:"CAM",age:28,ovr:80,nat:"Rusia"},
      {name:"Takumi Minamino",pos:"CAM",age:29,ovr:79,nat:"Japón"},
      {name:"Maghnes Akliouche",pos:"LW",age:22,ovr:77,nat:"Francia"},
      {name:"Folarin Balogun",pos:"ST",age:23,ovr:78,nat:"Estados Unidos"},
      {name:"Breel Embolo",pos:"ST",age:27,ovr:78,nat:"Suiza"},
      {name:"Wissam Ben Yedder",pos:"ST",age:33,ovr:80,nat:"Francia"},
      {name:"Eliesse Ben Seghir",pos:"RW",age:18,ovr:75,nat:"Marruecos"},
      {name:"Wilfried Singo",pos:"RB",age:23,ovr:77,nat:"Costa de Marfil"},
      {name:"Guillermo Maripán",pos:"CB",age:30,ovr:77,nat:"Chile"},
    ],
    "Niza": [
      {name:"Marcin Bułka",pos:"GK",age:24,ovr:77,nat:"Polonia"},
      {name:"Jonathan Bamba",pos:"RW",age:27,ovr:78,nat:"Francia"},
      {name:"Jean-Clair Todibo",pos:"CB",age:24,ovr:80,nat:"Francia"},
      {name:"Melvin Bard",pos:"LB",age:22,ovr:74,nat:"Francia"},
      {name:"Khéphren Thuram",pos:"CDM",age:22,ovr:80,nat:"Francia"},
      {name:"Hicham Boudaoui",pos:"CM",age:24,ovr:77,nat:"Argelia"},
      {name:"Alexis Claude-Maurice",pos:"LW",age:26,ovr:76,nat:"Francia"},
      {name:"Terem Moffi",pos:"ST",age:25,ovr:78,nat:"Nigeria"},
      {name:"Nicolas Pépé",pos:"RW",age:29,ovr:78,nat:"Costa de Marfil"},
      {name:"Jordan Lotomba",pos:"RB",age:24,ovr:75,nat:"Suiza"},
      {name:"Youcef Atal",pos:"RB",age:28,ovr:77,nat:"Argelia"},
      {name:"Maxime Estève",pos:"CB",age:22,ovr:73,nat:"Francia"},
      {name:"Pablo Rosario",pos:"CDM",age:27,ovr:75,nat:"Países Bajos"},
      {name:"Evann Guessand",pos:"ST",age:22,ovr:74,nat:"Francia"},
    ],
    "Lille": [
      {name:"Lucas Chevalier",pos:"GK",age:23,ovr:78,nat:"Francia"},
      {name:"Tiago Santos",pos:"RB",age:21,ovr:77,nat:"Portugal"},
      {name:"Alexsandro",pos:"CB",age:26,ovr:77,nat:"Brasil"},
      {name:"Leny Yoro",pos:"CB",age:18,ovr:78,nat:"Francia"},
      {name:"Gabriel Gudmundsson",pos:"LB",age:24,ovr:75,nat:"Suecia"},
      {name:"Benjamin André",pos:"CDM",age:33,ovr:78,nat:"Francia"},
      {name:"Angel Gomes",pos:"CM",age:23,ovr:77,nat:"Inglaterra"},
      {name:"Jonathan David",pos:"ST",age:24,ovr:83,nat:"Canadá"},
      {name:"Edon Zhegrova",pos:"RW",age:24,ovr:78,nat:"Kosovo"},
      {name:"Rémi Cabella",pos:"CAM",age:34,ovr:77,nat:"Francia"},
      {name:"Bafodé Diakité",pos:"CB",age:23,ovr:75,nat:"Francia"},
      {name:"Adam Ounas",pos:"RW",age:27,ovr:76,nat:"Argelia"},
      {name:"Hakon Haraldsson",pos:"CM",age:21,ovr:74,nat:"Islandia"},
      {name:"Mohamed Bayo",pos:"ST",age:25,ovr:74,nat:"Guinea"},
    ],
    "Lyon": [
      {name:"Anthony Lopes",pos:"GK",age:33,ovr:80,nat:"Portugal"},
      {name:"Malo Gusto",pos:"RB",age:21,ovr:78,nat:"Francia"},
      {name:"Castello Lukeba",pos:"CB",age:21,ovr:78,nat:"Francia"},
      {name:"Jake O'Brien",pos:"CB",age:23,ovr:75,nat:"Irlanda"},
      {name:"Nicolas Tagliafico",pos:"LB",age:31,ovr:79,nat:"Argentina"},
      {name:"Corentin Tolisso",pos:"CM",age:29,ovr:80,nat:"Francia"},
      {name:"Maxence Caqueret",pos:"CM",age:24,ovr:78,nat:"Francia"},
      {name:"Rayan Cherki",pos:"CAM",age:20,ovr:80,nat:"Francia"},
      {name:"Alexandre Lacazette",pos:"ST",age:32,ovr:81,nat:"Francia"},
      {name:"Ernest Nuamah",pos:"LW",age:20,ovr:74,nat:"Ghana"},
      {name:"Gift Orban",pos:"ST",age:22,ovr:75,nat:"Nigeria"},
      {name:"Wilfried Zaha",pos:"RW",age:31,ovr:79,nat:"Costa de Marfil"},
      {name:"Saël Kumbedi",pos:"RB",age:19,ovr:72,nat:"Francia"},
    ],
    "Lens": [
      {name:"Brice Samba",pos:"GK",age:29,ovr:80,nat:"República del Congo"},
      {name:"Przemysław Frankowski",pos:"RB",age:29,ovr:77,nat:"Polonia"},
      {name:"Kevin Danso",pos:"CB",age:25,ovr:79,nat:"Austria"},
      {name:"Jonathan Gradit",pos:"CB",age:30,ovr:76,nat:"Francia"},
      {name:"Deiver Machado",pos:"LB",age:32,ovr:75,nat:"Colombia"},
      {name:"Salis Abdul Samed",pos:"CDM",age:23,ovr:77,nat:"Ghana"},
      {name:"Elye Wahi",pos:"ST",age:21,ovr:78,nat:"Francia"},
      {name:"Angelo Fulgini",pos:"CAM",age:27,ovr:76,nat:"Francia"},
      {name:"Neil El Aynaoui",pos:"CM",age:22,ovr:75,nat:"Marruecos"},
      {name:"Facundo Medina",pos:"CB",age:25,ovr:77,nat:"Argentina"},
      {name:"Florian Sotoca",pos:"RW",age:33,ovr:74,nat:"España"},
      {name:"Wesley Saïd",pos:"ST",age:29,ovr:75,nat:"Francia"},
      {name:"Adrien Thomasson",pos:"CM",age:31,ovr:75,nat:"Francia"},
    ],
    "Rennes": [
      {name:"Steve Mandanda",pos:"GK",age:38,ovr:77,nat:"Francia"},
      {name:"Hamari Traoré",pos:"RB",age:30,ovr:76,nat:"Malí"},
      {name:"Arthur Theate",pos:"CB",age:23,ovr:78,nat:"Bélgica"},
      {name:"Warmed Omari",pos:"CB",age:24,ovr:75,nat:"Francia"},
      {name:"Adrien Truffert",pos:"LB",age:22,ovr:76,nat:"Francia"},
      {name:"Baptiste Santamaria",pos:"CDM",age:29,ovr:76,nat:"Francia"},
      {name:"Benjamin Bourigeaud",pos:"CM",age:30,ovr:78,nat:"Francia"},
      {name:"Martin Terrier",pos:"RW",age:27,ovr:79,nat:"Francia"},
      {name:"Arnaud Kalimuendo",pos:"ST",age:22,ovr:77,nat:"Francia"},
      {name:"Désiré Doué",pos:"LW",age:19,ovr:76,nat:"Francia"},
      {name:"Amine Gouiri",pos:"CAM",age:24,ovr:78,nat:"Argelia"},
      {name:"Karl Toko Ekambi",pos:"ST",age:31,ovr:76,nat:"Camerún"},
      {name:"Fabian Rieder",pos:"CM",age:22,ovr:74,nat:"Suiza"},
    ],
    "Estrasburgo": [
      {name:"Matz Sels",pos:"GK",age:32,ovr:76,nat:"Bélgica"},
      {name:"Alexander Djiku",pos:"CB",age:29,ovr:75,nat:"Ghana"},
      {name:"Gerzino Nyamsi",pos:"CB",age:27,ovr:74,nat:"Francia"},
      {name:"Jean-Ricner Bellegarde",pos:"CM",age:25,ovr:76,nat:"Francia"},
      {name:"Habib Diallo",pos:"ST",age:29,ovr:76,nat:"Senegal"},
      {name:"Emmanuel Emegha",pos:"ST",age:21,ovr:74,nat:"Países Bajos"},
      {name:"Dilane Bakwa",pos:"RW",age:21,ovr:73,nat:"Francia"},
      {name:"Zinedine Sissoko",pos:"CDM",age:24,ovr:74,nat:"Francia"},
      {name:"Thomas Delaine",pos:"LB",age:28,ovr:73,nat:"Francia"},
      {name:"Frédéric Guilbert",pos:"RB",age:30,ovr:73,nat:"Francia"},
    ],
    "Nantes": [
      {name:"Alban Lafont",pos:"GK",age:25,ovr:78,nat:"Francia"},
      {name:"Jean-Charles Castelletto",pos:"CB",age:29,ovr:74,nat:"Camerún"},
      {name:"Nicolas Pallois",pos:"CB",age:36,ovr:73,nat:"Francia"},
      {name:"Quentin Merlin",pos:"LB",age:21,ovr:73,nat:"Francia"},
      {name:"Pedro Chirivella",pos:"CDM",age:27,ovr:75,nat:"España"},
      {name:"Andrei Girotto",pos:"CDM",age:32,ovr:74,nat:"Brasil"},
      {name:"Moses Simon",pos:"LW",age:28,ovr:77,nat:"Nigeria"},
      {name:"Mostafa Mohamed",pos:"ST",age:26,ovr:76,nat:"Egipto"},
      {name:"Wylan Cyprien",pos:"CM",age:28,ovr:75,nat:"Francia"},
      {name:"Marcus Coco",pos:"RW",age:27,ovr:72,nat:"Francia"},
      {name:"Jaouen Hadjam",pos:"LB",age:21,ovr:72,nat:"Francia"},
      {name:"Samuel Moutoussamy",pos:"CM",age:27,ovr:73,nat:"Costa de Marfil"},
    ],
    "Brest": [
      {name:"Marco Bizot",pos:"GK",age:32,ovr:77,nat:"Países Bajos"},
      {name:"Brendan Chardonnet",pos:"CB",age:29,ovr:74,nat:"Francia"},
      {name:"Haris Belkebla",pos:"CDM",age:29,ovr:75,nat:"Argelia"},
      {name:"Pierre Lees-Melou",pos:"CM",age:30,ovr:76,nat:"Francia"},
      {name:"Steve Mounié",pos:"ST",age:29,ovr:75,nat:"Benín"},
      {name:"Mama Baldé",pos:"LW",age:28,ovr:75,nat:"Guinea-Bisáu"},
      {name:"Romain Del Castillo",pos:"RW",age:27,ovr:74,nat:"Francia"},
      {name:"Mahdi Camara",pos:"CM",age:26,ovr:74,nat:"Francia"},
      {name:"Mathias Pereira Lage",pos:"LW",age:27,ovr:74,nat:"Portugal"},
      {name:"Jeremy Le Douaron",pos:"ST",age:22,ovr:72,nat:"Francia"},
    ],
    "Toulouse": [
      {name:"Guillaume Restes",pos:"GK",age:19,ovr:74,nat:"Francia"},
      {name:"Logan Costa",pos:"CB",age:23,ovr:75,nat:"Portugal"},
      {name:"Gabriel Suazo",pos:"LB",age:26,ovr:74,nat:"Chile"},
      {name:"Stijn Spierings",pos:"CDM",age:28,ovr:74,nat:"Países Bajos"},
      {name:"Branco van den Boomen",pos:"CM",age:28,ovr:76,nat:"Países Bajos"},
      {name:"Thijs Dallinga",pos:"ST",age:23,ovr:76,nat:"Países Bajos"},
      {name:"Fares Chaïbi",pos:"CAM",age:21,ovr:75,nat:"Túnez"},
      {name:"Zakaria Aboukhlal",pos:"LW",age:23,ovr:74,nat:"Marruecos"},
      {name:"Rafael Ratão",pos:"RW",age:27,ovr:74,nat:"Brasil"},
      {name:"Mikkel Desler",pos:"RB",age:28,ovr:73,nat:"Dinamarca"},
      {name:"Moussa Diarra",pos:"CB",age:23,ovr:73,nat:"Malí"},
      {name:"Warren Kamanzi",pos:"CB",age:22,ovr:72,nat:"Ruanda"},
    ],
    "Auxerre": [
      {name:"Benoit Costil",pos:"GK",age:36,ovr:73,nat:"Francia"},
      {name:"Birama Touré",pos:"CDM",age:28,ovr:72,nat:"Francia"},
      {name:"Gauthier Hein",pos:"RW",age:26,ovr:71,nat:"Francia"},
      {name:"M'Baye Niang",pos:"ST",age:29,ovr:73,nat:"Senegal"},
      {name:"Lassine Sinayoko",pos:"LW",age:23,ovr:70,nat:"Malí"},
      {name:"Hamed Traoré",pos:"CM",age:24,ovr:73,nat:"Costa de Marfil"},
      {name:"Gideon Mensah",pos:"LB",age:24,ovr:70,nat:"Ghana"},
      {name:"Nuno Da Costa",pos:"ST",age:33,ovr:71,nat:"Cabo Verde"},
    ],
    "Le Havre": [
      {name:"Arthur Desmas",pos:"GK",age:26,ovr:73,nat:"Francia"},
      {name:"Abdoulaye Touré",pos:"CDM",age:31,ovr:72,nat:"Francia"},
      {name:"Daler Kuzyaev",pos:"CM",age:31,ovr:72,nat:"Rusia"},
      {name:"Yassine Kechta",pos:"ST",age:27,ovr:71,nat:"Marruecos"},
      {name:"Gautier Lloris",pos:"RB",age:34,ovr:70,nat:"Francia"},
      {name:"Christopher Opéri",pos:"CB",age:27,ovr:71,nat:"Francia"},
      {name:"Yoann Salmier",pos:"CB",age:29,ovr:71,nat:"Francia"},
      {name:"Loïs Openda",pos:"ST",age:24,ovr:74,nat:"Bélgica"},
      {name:"Andy Pembélé",pos:"RB",age:22,ovr:70,nat:"Francia"},
    ],
    "Angers": [
      {name:"Paul Bernardoni",pos:"GK",age:27,ovr:74,nat:"Francia"},
      {name:"Sofiane Boufal",pos:"LW",age:30,ovr:74,nat:"Marruecos"},
      {name:"Enzo Ebosse",pos:"CB",age:25,ovr:72,nat:"Camerún"},
      {name:"Himad Abdelli",pos:"CAM",age:24,ovr:72,nat:"Argelia"},
      {name:"Mohammed Tijani",pos:"ST",age:22,ovr:71,nat:"Sierra Leona"},
      {name:"Vincent Manceau",pos:"CB",age:28,ovr:71,nat:"Francia"},
      {name:"Abdallah Ndour",pos:"CM",age:23,ovr:70,nat:"Senegal"},
      {name:"Jimmy Cabot",pos:"RB",age:30,ovr:71,nat:"Francia"},
      {name:"Jordan Tell",pos:"RW",age:26,ovr:70,nat:"Francia"},
    ],
    "Lorient": [
      {name:"Yvon Mvogo",pos:"GK",age:29,ovr:74,nat:"Suiza"},
      {name:"Julien Laporte",pos:"CB",age:29,ovr:73,nat:"Francia"},
      {name:"Laurent Abergel",pos:"CDM",age:29,ovr:74,nat:"Francia"},
      {name:"Enzo Le Fée",pos:"CM",age:23,ovr:76,nat:"Francia"},
      {name:"Dango Ouattara",pos:"RW",age:22,ovr:76,nat:"Burkina Faso"},
      {name:"Ibrahima Koné",pos:"ST",age:23,ovr:74,nat:"Malí"},
      {name:"Bamba Dieng",pos:"ST",age:23,ovr:73,nat:"Senegal"},
      {name:"Vincent Le Goff",pos:"RB",age:30,ovr:72,nat:"Francia"},
      {name:"Stéphane Diarra",pos:"RW",age:23,ovr:71,nat:"Malí"},
    ],
    "Paris FC": [
      {name:"Léo Jardim",pos:"GK",age:28,ovr:72,nat:"Brasil"},
      {name:"Martin Satriano",pos:"ST",age:22,ovr:72,nat:"Uruguay"},
      {name:"Amine Bassi",pos:"CAM",age:26,ovr:72,nat:"Marruecos"},
      {name:"Colin Dagba",pos:"RB",age:25,ovr:70,nat:"Francia"},
      {name:"Eliaquim Mangala",pos:"CB",age:33,ovr:70,nat:"Francia"},
      {name:"Cheikh Keïta",pos:"CB",age:28,ovr:70,nat:"Guinea"},
      {name:"Morgan Guilavogui",pos:"CB",age:26,ovr:70,nat:"Francia"},
    ],
    "Metz": [
      {name:"Alexandre Oukidja",pos:"GK",age:33,ovr:73,nat:"Argelia"},
      {name:"Georges Mikautadze",pos:"ST",age:23,ovr:74,nat:"Georgia"},
      {name:"Farid Boulaya",pos:"CAM",age:30,ovr:73,nat:"Argelia"},
      {name:"Florent Mollet",pos:"CAM",age:32,ovr:73,nat:"Francia"},
      {name:"Dylan Bronn",pos:"CB",age:28,ovr:72,nat:"Túnez"},
      {name:"Kiki Kouyaté",pos:"CB",age:29,ovr:71,nat:"Malí"},
      {name:"Ibrahima Niane",pos:"ST",age:26,ovr:72,nat:"Senegal"},
      {name:"Digbo Gbamin",pos:"CDM",age:27,ovr:71,nat:"Costa de Marfil"},
    ],

  };

  // Fusiona ROSTERS (PL + Bundesliga + Ligue 1) en SQUADS (LaLiga + Serie A de data.js)
  window.FC.data.SQUADS = Object.assign({}, window.FC.data.SQUADS || {}, window.FC.data.ROSTERS);

})();
